parameters:
services:
    _defaults:
        autowire: true
        autoconfigure: true
    OSModel\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
    OSModel\Repository\:
        resource: '../../Repository'
        tags: ['doctrine.repository_service']
    OSModel\Manager\OSModelManager:
        arguments:
            - '@Doctrine\Common\Persistence\ObjectManager'
            - 'OSModel\Entity\OSModel'
